# setup
library(here)
library(rmarkdown)

# You can find the correct directory by typing Sys.getenv("RSTUDIO_PANDOC")
Sys.setenv(RSTUDIO_PANDOC = "C:/Program Files/RStudio/bin/")

source("scripts/load_groupshare_files.R")

# function to render parameters and save html output to file
render_report = function(data, ministry, share, collected) {
  rmarkdown::render(
    here("scripts", "enhanced_sfp_report_share.Rmd"), params = list(
      data = data,
      ministry = ministry,
      share = share,
      collected = collected
    ),
    output_file = paste0("SFP_Enhanced_Report_", ministry, "_", share, "_", collected, ".pdf"),
    output_dir = here("output"),
  )
}

# render, stating parameters
# Ministry of AF
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04001", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04002", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04003", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04004", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04005", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04012", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04013", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04014", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04040", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04043", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04047", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04048", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04056", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04100", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04101", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04102", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04149", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04777", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_AF_SFP_Enhanced_Data.csv", "AF", "S04778", "YYYY-MM-DD")
gc()

# Ministry of EMLI
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6201", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6202", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6203", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6204", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6205", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6206", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6207", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6208", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6209", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6210", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6211", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6212", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6213", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6214", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6215", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6216", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6217", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6218", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6219", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6220", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6221", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6222", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6223", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6224", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6225", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6226", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S6227", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_EMLI_SFP_Enhanced_Data.csv", "EMLI", "S62777", "YYYY-MM-DD")
gc()


# Ministry of ENV
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40008", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40009", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40010", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40011", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40012", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40013", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40014", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40015", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40016", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40017", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40018", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40019", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40020", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40021", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40022", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40023", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40024", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40025", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40026", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40028", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40029", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40030", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40031", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40032", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40033", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40034", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40035", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40036", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40037", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40038", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40039", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40040", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40041", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40042", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40043", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40044", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40045", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40047", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40048", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40049", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40050", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40051", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40052", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40053", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40054", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40055", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40056", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40057", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40058", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40059", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40060", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40061", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40063", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40064", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40065", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40066", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40068", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40069", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40070", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40071", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40072", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40073", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40074", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40075", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40083", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40086", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40093", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40133", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40142", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40143", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40086", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40152", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40153", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40154", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40155", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40172", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40173", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40182", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40183", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40184", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40193", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40195", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40203", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40204", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40205", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40206", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40207", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40208", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_ENV_SFP_Enhanced_Data.csv", "ENV", "S40777", "YYYY-MM-DD")
gc()

# Ministry of Forests
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63001", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63002", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63004", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63005", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63006", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63007", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63008", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63009", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63010", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63011", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63012", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63013", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63014", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63015", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63016", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63017", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63018", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63019", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63020", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63021", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63022", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63023", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63024", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63025", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63026", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63027", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63028", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63029", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63030", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63031", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63032", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63033", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63034", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63035", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63036", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63038", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63039", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63040", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63041", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63042", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63043", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63044", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63045", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63046", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63047", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63048", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63049", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63050", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63051", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63052", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63053", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63054", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63055", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63056", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63057", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63058", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63059", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63060", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63061", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63062", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63063", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63064", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63065", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63066", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63067", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63068", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63069", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63070", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63071", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63072", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63073", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63074", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63075", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63076", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63077", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63078", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63079", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63081", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63082", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63083", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63084", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63085", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63086", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63087", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63088", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63089", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63090", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63091", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63092", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63093", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63094", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63095", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63096", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63097", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63098", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63099", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63100", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63101", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63102", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63103", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63104", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63105", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63106", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63107", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63108", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63109", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63110", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63111", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63112", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63114", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63115", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63116", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63117", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63118", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63119", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63120", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63121", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63122", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63123", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63124", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63125", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63126", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63127", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63128", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63129", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63130", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63131", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63132", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63133", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63201", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63202", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63777", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_FOR_SFP_Enhanced_Data.csv", "FOR", "S63888", "YYYY-MM-DD")
gc()

# Ministry of IRR
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09200", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09201", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09202", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09203", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09204", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09205", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09206", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09207", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09208", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09209", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09210", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09211", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09212", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S09213", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_IRR_SFP_Enhanced_Data.csv", "IRR",  "S092777", "YYYY-MM-DD")
gc()

# Ministry of WLRS
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09000", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09001", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09002", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09003", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09004", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09005", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09006", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09007", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09008", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09009", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09010", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_WLRS_SFP_Enhanced_Data.csv", "WLRS",  "S09777", "YYYY-MM-DD")
gc()

# function to render parameters and save html output to file
render_report = function(data, ministry, share, collected) {
  rmarkdown::render(
    here("scripts", "enhanced_sfp_report_share_bcws.Rmd"), params = list(
      data = data,
      ministry = ministry,
      share = share,
      collected = collected
    ),
    output_file = paste0("SFP_Enhanced_Report_", ministry, "_", share, "_", collected, ".pdf"),
    output_dir = here("output"),
  )
}

# BC Wildfire Service
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65001", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65002", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65003", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65004", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65005", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65006", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65007", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65008", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65009", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65010", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65011", "YYYY-MM-DD")
gc()
render_report("YYYY_MM_DD_BCWS_SFP_Enhanced_Data.csv", "BCWS", "S65777", "YYYY-MM-DD")
gc()
