library(tibble)
library(dplyr)

accountability_lookup <- tibble(
  folder_path = c(
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\Asset Mgmt Fire Centres",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\Chainsaw Administration",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\Communications Working Group",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\CWS",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\CWS Database",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\Fire Equipment Committee",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\Predictive Services",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\Prescribed Fire",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\PWCC Aviation Management",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\PWCC Operations",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\Structure Protection Program",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Project\\WRMP",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Publish\\Corporate Wildfire Services",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Publish\\Fire Investigation",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Publish\\PWCC",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Publish\\Systems",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Accounts Payable",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Air Tanker",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\All Hazards",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Aviation",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Corporate Wildfire Serv",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Fire Investigation",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Fire Investigation HR",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Fire Operations",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Legislation and Policy - FNIR",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Management",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Media Communications",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\PWCC_Contracts",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Structure Protection",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Training",
    "\\\\sfp.idir.bcgov\\S165\\S65002\\!Workgrp\\Wildfire Risk",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Project\\CFED",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Publish\\CFED",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Administration",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\BCWS FORMS",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\DCO",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Equipment",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\FINADMIN_ScanDocs",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Finance",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Fleet",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\HR",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\IMIS",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Kit Lists",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Maintenance & Retrieval",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Mobile Camps",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Pictures",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Purchasing",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Security",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\SOG-SOP",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Specificiations",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Warehousing",
    "\\\\sfp.idir.bcgov\\s165\\s65010\\!Workgrp\\Work Schedules and Standby Lists",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Project\\Corporate Wildfire Services",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Project\\FN Cultural Sites",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Project\\Policy",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Project\\Prevention Promotional Material",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Project\\Recruitment",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Project\\Wildfire Claims",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Publish\\Common Files\\1800 TEAMS and RRT",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Publish\\Common Files\\Communications and Engagement - Prevention",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Publish\\Common Files\\FireScience",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Publish\\Common Files\\Presentation",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Publish\\Common Files\\Presentation\\Fire Management Planning",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Publish\\Common Files\\Wildfire Prevention Community of Practice",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Publish\\Common Files\\WxData",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\AdminMgrs",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Asset Mgmt",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Assets",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\BCWS Legal",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Communications and Engagement _Prevention",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Corporate Priorites and Communications",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\CorpServ",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Cost Recovery",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\CS_Managers",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Cultural and Prescribed Fire",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\CWS HQ",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\CWS Leadership Team",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\DEC Project",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Director, Corporate Governance",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\ELT",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Executive Support",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Finance",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Financial Reviews",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Fire Management",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Fire Sciences",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Fire Weather Program",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\HQ Fatigue Tracker",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\International",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Jutland",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Media",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\OTBH Determinations",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Prevention",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Prevention_Mgmt",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Procurement",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\PWRC -1-800 Centre",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\PWRC Supervisor",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\PWRC Team Lead",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\R and I 2018",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\SAC",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Strategic Engagement",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Strategic Initiatives",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Training",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Wildfire Land Based Recovery",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Wildfire Managers",
    "\\\\sfp.idir.bcgov\\s165\\s65011\\!Workgrp\\Wildfire Risk Information Governance",
    "\\\\bcwsdata.nrs.bcgov\\training$\\Aviation",
    "\\\\bcwsdata.nrs.bcgov\\training$\\Chainsaw",
    "\\\\bcwsdata.nrs.bcgov\\training$\\Danger Tree",
    "\\\\bcwsdata.nrs.bcgov\\training$\\Finance",
    "\\\\bcwsdata.nrs.bcgov\\training$\\Provincial",
    "\\\\bcwsdata.nrs.bcgov\\training$\\PWCC G Drive files",
    "\\\\bcwsdata.nrs.bcgov\\training$\\Recruiting",
    "\\\\bcwsdata.nrs.bcgov\\training$\\RX Fire Planning",
    "\\\\bcwsdata.nrs.bcgov\\training$\\Safety",
    "\\\\bcwsdata.nrs.bcgov\\training$\\TEAMS",
    "\\\\bcwsdata.nrs.bcgov\\training$\\Training Plans",
    "\\\\bcwsdata.nrs.bcgov\\training$\\WSBC"
  ),
  `Accountable Excluded Manager Position` = c(
    "Senior Assets Manager",
    "Manager Organizational Development",
    "Manager Communications and Engagement",
    "Manager Corporate Wildfire Service",
    "Manager Corporate Wildfire Service",
    "TBD",
    "Deputy Director Predictive Services Unit",
    "Manager Wildfire Prevention, Crx",
    "Manager Provincial Operations Preparedness",
    "Manager Provincial Operations Response",
    "Manager Provincial Operations Preparedness",
    "Manager Wildfire Prevention, Crx",
    "Manager Corporate Wildfire Service",
    "Manager Wildfire Risk",
    "Manager Provincial Operations Response",
    "Director, Radio, Technology and Field Services",
    "Manager Corporate Wildfire Service",
    "Manager Provincial Operations Response",
    "Manager Provincial Operations Preparedness",
    "Manager Provincial Operations Response",
    "Manager Corporate Wildfire Service",
    "Manager Wildfire Risk",
    "Manager Wildfire Risk",
    "Manager Provincial Operations Response",
    "Deputy Manager Wildfire Risk",
    "Executive Coordinator",
    "Manager Communications and Engagement",
    "Manager Provincial Operations Preparedness",
    "Manager Provincial Operations Preparedness",
    "Manager Organizational Development",
    "Manager Wildfire Risk",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Senior Manager Assets",
    "Manager Corporate Wildfire Service",
    "Manager First Nations and Indigenous Relations",
    "Manager Wildfire Risk",
    "Manager Prevention, Cultural & Rx Fire",
    "Director People Culture Capacity",
    "Manager Wildfire Risk",
    "Manager Communications and Engagement",
    "xxx",
    "Manager Prevention, Cultural & Rx Fire",
    "xxx",
    "Manager Prevention, Cultural & Rx Fire",
    "xxx",
    "xxx",
    "Manager Corporate Wildfire Service",
    "Senior Assets Manager",
    "Senior Assets Manager",
    "Manager Wildfire Risk",
    "xxx",
    "xxx",
    "Manager Corporate Wildfire Service",
    "Manager Corporate Wildfire Service",
    "Manager Corporate Wildfire Service",
    "Manager Prevention, Cultural & Rx Fire",
    "Manager Corporate Wildfire Service",
    "Manager Corporate Wildfire Service",
    "Manager Corporate Wildfire Service",
    "Director Corporate Governance",
    "Executive Director",
    "Executive Coordinator",
    "Manager Finance and Corporate Admin",
    "Manager Corporate Wildfire Service",
    "Manager Prevention, Cultural & Rx Fire",
    "Manager Prevention, Cultural & Rx Fire",
    "Deputy Director Predictive Services Unit",
    "xxx",
    "xxx",
    "xxx",
    "Manager Communications and Engagement",
    "Manager Wildfire Risk",
    "Manager Prevention, Cultural & Rx Fire",
    "Manager Prevention, Cultural & Rx Fire",
    "Manager Corporate Wildfire Service",
    "Manager Communications and Engagement",
    "Manager Communications and Engagement",
    "Manager Communications and Engagement",
    "Manager  Strategiv Initiative and Innovation",
    "Manager Strategic Initiatives and Innovation",
    "xxx",
    "Manager Strategic Initiatives and Innovation",
    "Manager Organizational Development",
    "Manager Wildfire Land Based Recovery",
    "xxx",
    "Manager Wildfire Risk",
    "TBD",
    "TBD",
    "TBD",
    "TBD",
    "TBD",
    "Manager Provincial Operations Response",
    "TBD",
    "TBD",
    "TBD",
    "TBD",
    "TBD",
    "TBD"
  ),
  `Accountable Excluded Manager Incumbent` = c(
    "Kayla Cockle",
    "Kyle Young",
    "Forrest Tower",
    "Shauna Weir",
    "Shauna Weir",
    "TBD",
    "Brent Martin",
    "Vacant",
    "Derek Williams (Baskerville base)",
    "Todd Nessman",
    "Derek Williams (Baskerville base)",
    "Vacant",
    "Shauna Weir",
    "Kathleen Werstiuk",
    "Todd Nessman",
    "Joel Murphy",
    "Shauna Weir",
    "Todd Nessman",
    "Derek Williams (Baskerville base)",
    "Todd Nessman",
    "Shauna Weir",
    "Kathleen Werstiuk",
    "Kathleen Werstiuk",
    "Todd Nessman",
    "Angela Brotchie",
    "Courtney Hawkins",
    "Forrest Tower",
    "Derek Williams (Baskerville base)",
    "Derek Williams (Baskerville base)",
    "Kyle Young",
    "Kathleen Werstiuk",
    "Kayla Cockle",
    "Kayla Cockle",
    "Kayla Cockle",
    "Kayla Cockle",
    "Kayla Cockle",
    'Kayla Cockle',
    "Kayla Cockle",
    "Kayla Cockle",
    'Kayla Cockle',
    "Kayla Cockle",
    "Kayla Cockle",
    'Kayla Cockle',
    'Kayla Cockle',
    'Kayla Cockle',
    'Kayla Cockle',
    'Kayla Cockle',
    'Kayla Cockle',
    'Kayla Cockle',
    'Kayla Cockle',
    'Kayla Cockle',
    'Kayla Cockle',
    "Shauna Weir",
    "Renae Real",
    "Kathleen Werstiuk",
    "Vacant",
    "Gordon Asselin",
    "Kathleen Werstiuk",
    "Vacant",
    "xxx",
    "Vacant",
    "xxx",
    "Vacant",
    "xxx",
    "xxx",
    "Shauna Weir",
    "Kayla Cockle",
    "Kayla Cockle",
    "Kathleen Werstiuk",
    "xxx",
    "xxx",
    "Shauna Weir",
    "Shauna Weir",
    "Shauna Weir",
    "Vacant",
    "Shauna Weir",
    "Shauna Weir",
    "Shauna Weir",
    "Dave Fleming",
    "David Greer",
    "Courntey Hawkins",
    "Robert Bradford",
    "Shauna Weir",
    "Vacant",
    "Vacant",
    "Brent Martin",
    "xxx",
    "xxx",
    "xxx",
    "Vacant",
    "Kathleen Werstiuk",
    "Vacant",
    "Vacant",
    "Shauna Weir",
    "Vacant",
    "Vacant",
    "Vacant",
    "Kyle Todoruk",
    "Kyle Todoruk",
    "xxx",
    "Kyle Todoruk",
    "Kyle Young",
    "Reg Nolander",
    "xxx",
    "Kathleen Werstiuk",
    "TBD",
    "TBD",
    "TBD",
    "TBD",
    "TBD",
    "Todd Nessman",
    "TBD",
    "TBD",
    "TBD",
    "TBD",
    "TBD",
    "TBD"
  )
) %>%
  mutate(folder_path = tolower(folder_path))